# $:.push File.expand_path("../lib", __FILE__)

# Maintain your gem's version:

# Describe your gem and declare its dependencies:
Gem::Specification.new do |s|
  s.name        = "moip-ruby"
  s.version     = "0.1.2"
  s.authors     = ["TODO: Your name"]
  s.email       = ["TODO: Your email"]
  s.homepage    = "TODO"
  s.summary     = "TODO: Summary of ImentoreCms."
  s.description = "TODO: Description of ImentoreCms."

  s.files = Dir["{lib}/**/*"] + ["Rakefile", "README.markdown"]

  s.add_dependency(%q<rspec>, ["~> 2.1.0"])
  s.add_dependency(%q<nokogiri>, ["~> 1.5.2"])
  s.add_dependency(%q<httparty>, ["~> 0.8.3"])
  s.add_dependency(%q<activesupport>, [">= 3.2.3"])
end

# # Generated by jeweler
# # DO NOT EDIT THIS FILE DIRECTLY
# # Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# # -*- encoding: utf-8 -*-

# Gem::Specification.new do |s|
#   s.name = %q{moip-ruby}
#   s.version = "0.1.2"

#   s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
#   s.authors = ["Guilherme Nascimento"]
#   s.date = %q{2012-05-29}
#   s.description = %q{Gem para utilização da API MoIP}
#   s.email = %q{guilherme.ruby@gmail.com}
#   s.extra_rdoc_files = [
#     "LICENSE",
#     "README.markdown"
#   ]
#   s.files = [
#     ".document",
#     "Gemfile",
#     "Gemfile.lock",
#     "LICENSE",
#     "README.markdown",
#     "Rakefile",
#     "VERSION",
#     "lib/moip.rb",
#     "lib/moip/client.rb",
#     "lib/moip/direct_payment.rb",
#     "moip-ruby.gemspec",
#     "spec/moip_spec.rb"
#   ]
#   s.homepage = %q{http://github.com/guinascimento/moip}
#   s.require_paths = ["lib"]
#   s.summary = %q{Gem para utilização da API MoIP}

#   # if s.respond_to? :specification_version then
#   #   s.specification_version = 3

#   #   if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
#   #     s.add_runtime_dependency(%q<moip-ruby>, [">= 0"])
#   #     s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_runtime_dependency(%q<nokogiri>, ["~> 1.5.2"])
#   #     s.add_runtime_dependency(%q<httparty>, ["~> 0.8.3"])
#   #     s.add_runtime_dependency(%q<activesupport>, [">= 3.2.3"])
#   #   else
#   #     s.add_dependency(%q<moip-ruby>, [">= 0"])
#   #     s.add_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_dependency(%q<rspec>, ["~> 2.1.0"])
#   #     s.add_dependency(%q<nokogiri>, ["~> 1.5.2"])
#   #     s.add_dependency(%q<httparty>, ["~> 0.8.3"])
#   #     s.add_dependency(%q<activesupport>, [">= 3.2.3"])
#   #   end
#   # else
#     s.add_dependency(%q<rspec>, ["~> 2.1.0"])
#     s.add_dependency(%q<nokogiri>, ["~> 1.5.2"])
#     s.add_dependency(%q<httparty>, ["~> 0.8.3"])
#     s.add_dependency(%q<activesupport>, [">= 3.2.3"])
#   # end
# end

